apiVersion: v1
kind: Service
metadata:
  name: { { .Values.appName } }
  namespace: webapps
  labels:
    app: { { .Values.appName } }
spec:
  selector:
    app: { { .Values.appName } }
  ports:
    - name: http
      port: 80
      targetPort: { { .Values.port } }
