name: CD - Azure

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'The name of the app to deploy'
        required: true
      environment:
        description: 'Target environment for publication'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    env:
      APP: ${{ inputs.app }}
      ENV: ${{ inputs.environment }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Config Path
      run: echo "CONFIG_PATH=apps/$APP/$ENV.yaml" >> $GITHUB_ENV
    - name: Display Config Path
      run: echo "$CONFIG_PATH"
    - name: Build Summary
      run: echo "### $APP published in $ENV! :rocket:" >> $GITHUB_STEP_SUMMARY
