name: CD - Azure

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'The name of the app to deploy'
        required: true
      environment:
        description: 'Target environment for publication'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    env:
      APP: ${{ inputs.app }}
      ENV: ${{ inputs.environment }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Config Path
      run: echo "CONFIG_PATH=apps/$APP/$ENV.yaml" >> $GITHUB_ENV
    - name: Check if Config File Exists
      run: |
        if [ ! -f "$CONFIG_PATH" ]; then
          exit 1
        fi
    - name: Fail Workflow If Config File Doesn't Exist
      if: ${{ failure() }}
      uses: actions/github-script@v3
      with:
        script: |
          const configPath = process.env.CONFIG_PATH;
          core.setFailed(`Configuration file '${configPath}' does not exist. Make sure the app name given matches the directory of the application in apps/ and try again.`)
    - name: Build Summary
      run: echo "### $APP deployed in $ENV (WIP)! :rocket:" >> $GITHUB_STEP_SUMMARY
