name: CD - Azure

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'The name of the app to deploy'
        required: true
      environment:
        description: 'Target environment for publication'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    env:
      APP: ${{ inputs.app }}
      ENV: ${{ inputs.environment }}
      RG_NAME: ${{ vars.RG_NAME }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Config Path
      run: echo "CONFIG_PATH=apps/$APP/$ENV.yaml" >> $GITHUB_ENV
    - name: Check if Config File Exists
      run: |
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "Error: Configuration file '$CONFIG_PATH' does not exist. Make sure the app name given matches the directory of the application in apps/ and try again."
          echo "::error::Configuration file '$CONFIG_PATH' does not exist. Make sure the app name given matches the directory of the application in apps/ and try again."
          exit 1
        else
          echo "Configuration file exists: $CONFIG_PATH"
        fi
      shell: bash
      env:
        CONFIG_PATH: ${{ env.CONFIG_PATH }}
        
    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
         resource-group: ${{ env.RG_NAME }}
         cluster-name: ${{ env.CLUSTER_NAME }}
    - name: Deploy with Helm
      run: |
        helm upgrade $APP-release chart/ -i -f $CONFIG_PATH -n webapps --create-namespace

